# Generated by Django 6.0.3 on 2026-03-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecord',
            name='category',
            field=models.CharField(choices=[('meeting', 'Совещание'), ('instruction', 'Инструкция'), ('archive', 'Архив'), ('other', 'Прочее')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='audiorecord',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
