# Generated by Django 6.0.3 on 2026-03-30 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiorecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Аудиозапись', 'verbose_name_plural': 'Аудиозаписи'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_records', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='audiorecord',
            name='category',
            field=models.CharField(choices=[('meeting', 'Совещание'), ('instruction', 'Инструкция'), ('archive', 'Архив'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Категория'),
        ),
    ]
