# Generated by Django 6.0.3 on 2026-03-30 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_audiorecord_is_private_record_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.audiorecord'),
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
