# Generated by Django 6.0.3 on 2026-04-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecord',
            name='tags',
            field=models.CharField(blank=True, help_text='Введите теги через запятую', max_length=255, verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='audiorecord',
            name='category',
            field=models.CharField(choices=[('concentration', 'Для концентрации (Lo-Fi, Классика)'), ('pro', 'Профессиональный контент (Вебинары, Акты)'), ('relax', 'Психологическая разгрузка (Природа, Медитация)'), ('meeting', 'Совещание / Протокол'), ('other', 'Прочее')], default='Другое', max_length=20, verbose_name='Категория'),
        ),
    ]
