# Generated by Django 6.0.4 on 2026-04-08 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_postcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='post',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.audiorecord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcomment',
            name='timestamp',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcomment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='text',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
