# Generated by Django 6.0.4 on 2026-04-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_feedcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст новости')),
                ('is_important', models.BooleanField(default=False, verbose_name='Закрепить на главной')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость портала',
                'verbose_name_plural': 'Новости портала',
                'ordering': ['-is_important', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegionalStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Название показателя')),
                ('value', models.CharField(max_length=50, verbose_name='Значение')),
                ('trend', models.CharField(choices=[('up', 'Вверх'), ('down', 'Вниз'), ('stable', 'Стабильно')], max_length=10, verbose_name='Тренд')),
            ],
            options={
                'verbose_name': 'Статистический показатель',
                'verbose_name_plural': 'Статистические показатели',
            },
        ),
    ]
