# Generated by Django 6.0.4 on 2026-04-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_portalnews_regionalstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecord',
            name='bitrate',
            field=models.CharField(default='128 kbps', max_length=20, verbose_name='Битрейт'),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='file_format',
            field=models.CharField(default='MP3', max_length=10, verbose_name='Формат'),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='file_size',
            field=models.CharField(default='0 MB', max_length=20, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Проверено архивом'),
        ),
        migrations.AddField(
            model_name='audiorecord',
            name='security_level',
            field=models.CharField(default='Только для внутреннего пользования', max_length=50, verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='audiorecord',
            name='tags',
            field=models.CharField(blank=True, default='Аналитика, Голос', max_length=255, verbose_name='Теги'),
        ),
    ]
