# Generated by Django 6.0.4 on 2026-04-11 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_audiorecord_bitrate_audiorecord_file_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audio_docs/', verbose_name='Документ')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.audiorecord', verbose_name='Основная запись')),
            ],
            options={
                'verbose_name': 'Дополнительный документ',
                'verbose_name_plural': 'Дополнительные документы',
            },
        ),
    ]
