# Generated by Django 6.0.4 on 2026-05-13 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_audiorecord_file_format_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiorecord',
            name='file',
            field=models.FileField(upload_to='audio_records/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Файл'),
        ),
    ]
